<?php

//exports alias path
function designssquare_alias_path_uuid_node_features_export_render_alter(&$export, $node, $module){
        if(isset($node->nid)){
            $alias_url = drupal_get_path_alias('node/'.$node->nid);
            $export->alias_url = $alias_url;
        }
}

//save temporary alias path in variable mapped to node via node's uuid
function designssquare_alias_path_uuid_node_features_rebuild_alter(&$node, $module){
        if(isset($node->alias_url)){
            $alias_url = $node->alias_url;
            variable_set('node_path_alias_'.$node->uuid, $alias_url);
            unset($node->alias_url);
        }
}

//inserts alias path for each node
function designssquare_alias_path_pathauto_alias_alter(&$alias, array &$context) {
    $node = null;
    //@ToDo Insert alias path for other times than 'node' such as 'taxanomy', 'user'
    $pos = strpos($context['source'],'node/');

    if($pos == 0){
        $id = substr($context['source'], 5);
        $node = node_load($id);
        $alias_url = (isset($node->uuid)) ? variable_get('node_path_alias_'.$node->uuid, FALSE) : FALSE;
    }else{
        $alias_url = FALSE;
    }

    $alias = ($alias_url) ? $alias_url : $alias;
}